[package]
name = "bnl"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
miniz_oxide = "0.8.9"
num_enum = "0.7.4"

bcndecode = "0.2"
png = "0.17.16"

[lib]
name = "bnl"
path = "src/lib.rs"

[[bin]]
name = "bnltool"
path = "src/bin/main.rs"
